/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MatrixUtil */

#ifndef _Included_MatrixUtil
#define _Included_MatrixUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MatrixUtil
 * Method:    multiply
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_MatrixUtil_multiply
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
